CREATE TABLE IF NOT EXISTS product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  cost INT NOT NULL
);

CREATE TABLE IF NOT EXISTS team (
  id INT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS team_member (
  id INT AUTO_INCREMENT PRIMARY KEY,
  team_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE IF NOT EXISTS stops (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  `lines` VARCHAR(255) NOT NULL DEFAULT '',
  transfer_lines VARCHAR(255) NOT NULL DEFAULT '',
  image_url VARCHAR(255),
  is_transfer BOOLEAN NOT NULL DEFAULT FALSE,
  x DECIMAL(10, 6),
  y DECIMAL(10, 6),
  wheelchair_accessible BOOLEAN NOT NULL DEFAULT FALSE,
  has_shelter BOOLEAN NOT NULL DEFAULT FALSE,
  has_bench BOOLEAN NOT NULL DEFAULT FALSE,
  has_ticket_machine BOOLEAN NOT NULL DEFAULT FALSE,
  has_display BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO team (id, name) VALUES (1, 'Macka Cervene')
  ON DUPLICATE KEY UPDATE name = VALUES(name);

DELETE FROM team_member WHERE team_id = 1;
INSERT INTO team_member (team_id, name) VALUES (1, 'Ema'), (1, 'Amálie');
